/*
 * iEngage 2.0 API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iengage.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.iengage.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * InteractionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-27T14:33:47.218+05:30")
public class InteractionResponse {
  @SerializedName("responseId")
  private Long responseId = null;

  @SerializedName("responseDescription")
  private String responseDescription = null;

  @SerializedName("interactionId")
  private Long interactionId = null;

  @SerializedName("respondingUser")
  private User respondingUser = null;

  @SerializedName("createdDate")
  private DateTime createdDate = null;

  @SerializedName("isMarkedResponse")
  private Boolean isMarkedResponse = false;

  @SerializedName("noOfLikes")
  private Integer noOfLikes = null;

  @SerializedName("noOfDislikes")
  private Integer noOfDislikes = null;

  @SerializedName("replyCount")
  private Integer replyCount = null;

  @SerializedName("isLiked")
  private Boolean isLiked = false;

  @SerializedName("isDisliked")
  private Boolean isDisliked = false;

  @SerializedName("interactionType")
  private String interactionType = null;

  public InteractionResponse responseId(Long responseId) {
    this.responseId = responseId;
    return this;
  }

   /**
   * Get responseId
   * @return responseId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getResponseId() {
    return responseId;
  }

  public void setResponseId(Long responseId) {
    this.responseId = responseId;
  }

  public InteractionResponse responseDescription(String responseDescription) {
    this.responseDescription = responseDescription;
    return this;
  }

   /**
   * Get responseDescription
   * @return responseDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResponseDescription() {
    return responseDescription;
  }

  public void setResponseDescription(String responseDescription) {
    this.responseDescription = responseDescription;
  }

  public InteractionResponse interactionId(Long interactionId) {
    this.interactionId = interactionId;
    return this;
  }

   /**
   * Get interactionId
   * @return interactionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getInteractionId() {
    return interactionId;
  }

  public void setInteractionId(Long interactionId) {
    this.interactionId = interactionId;
  }

  public InteractionResponse respondingUser(User respondingUser) {
    this.respondingUser = respondingUser;
    return this;
  }

   /**
   * Get respondingUser
   * @return respondingUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getRespondingUser() {
    return respondingUser;
  }

  public void setRespondingUser(User respondingUser) {
    this.respondingUser = respondingUser;
  }

  public InteractionResponse createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public InteractionResponse isMarkedResponse(Boolean isMarkedResponse) {
    this.isMarkedResponse = isMarkedResponse;
    return this;
  }

   /**
   * Get isMarkedResponse
   * @return isMarkedResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsMarkedResponse() {
    return isMarkedResponse;
  }

  public void setIsMarkedResponse(Boolean isMarkedResponse) {
    this.isMarkedResponse = isMarkedResponse;
  }

  public InteractionResponse noOfLikes(Integer noOfLikes) {
    this.noOfLikes = noOfLikes;
    return this;
  }

   /**
   * Get noOfLikes
   * @return noOfLikes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNoOfLikes() {
    return noOfLikes;
  }

  public void setNoOfLikes(Integer noOfLikes) {
    this.noOfLikes = noOfLikes;
  }

  public InteractionResponse noOfDislikes(Integer noOfDislikes) {
    this.noOfDislikes = noOfDislikes;
    return this;
  }

   /**
   * Get noOfDislikes
   * @return noOfDislikes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNoOfDislikes() {
    return noOfDislikes;
  }

  public void setNoOfDislikes(Integer noOfDislikes) {
    this.noOfDislikes = noOfDislikes;
  }

  public InteractionResponse replyCount(Integer replyCount) {
    this.replyCount = replyCount;
    return this;
  }

   /**
   * Get replyCount
   * @return replyCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReplyCount() {
    return replyCount;
  }

  public void setReplyCount(Integer replyCount) {
    this.replyCount = replyCount;
  }

  public InteractionResponse isLiked(Boolean isLiked) {
    this.isLiked = isLiked;
    return this;
  }

   /**
   * Get isLiked
   * @return isLiked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsLiked() {
    return isLiked;
  }

  public void setIsLiked(Boolean isLiked) {
    this.isLiked = isLiked;
  }

  public InteractionResponse isDisliked(Boolean isDisliked) {
    this.isDisliked = isDisliked;
    return this;
  }

   /**
   * Get isDisliked
   * @return isDisliked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsDisliked() {
    return isDisliked;
  }

  public void setIsDisliked(Boolean isDisliked) {
    this.isDisliked = isDisliked;
  }

  public InteractionResponse interactionType(String interactionType) {
    this.interactionType = interactionType;
    return this;
  }

   /**
   * Get interactionType
   * @return interactionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInteractionType() {
    return interactionType;
  }

  public void setInteractionType(String interactionType) {
    this.interactionType = interactionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InteractionResponse interactionResponse = (InteractionResponse) o;
    return Objects.equals(this.responseId, interactionResponse.responseId) &&
        Objects.equals(this.responseDescription, interactionResponse.responseDescription) &&
        Objects.equals(this.interactionId, interactionResponse.interactionId) &&
        Objects.equals(this.respondingUser, interactionResponse.respondingUser) &&
        Objects.equals(this.createdDate, interactionResponse.createdDate) &&
        Objects.equals(this.isMarkedResponse, interactionResponse.isMarkedResponse) &&
        Objects.equals(this.noOfLikes, interactionResponse.noOfLikes) &&
        Objects.equals(this.noOfDislikes, interactionResponse.noOfDislikes) &&
        Objects.equals(this.replyCount, interactionResponse.replyCount) &&
        Objects.equals(this.isLiked, interactionResponse.isLiked) &&
        Objects.equals(this.isDisliked, interactionResponse.isDisliked) &&
        Objects.equals(this.interactionType, interactionResponse.interactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseId, responseDescription, interactionId, respondingUser, createdDate, isMarkedResponse, noOfLikes, noOfDislikes, replyCount, isLiked, isDisliked, interactionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InteractionResponse {\n");
    
    sb.append("    responseId: ").append(toIndentedString(responseId)).append("\n");
    sb.append("    responseDescription: ").append(toIndentedString(responseDescription)).append("\n");
    sb.append("    interactionId: ").append(toIndentedString(interactionId)).append("\n");
    sb.append("    respondingUser: ").append(toIndentedString(respondingUser)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    isMarkedResponse: ").append(toIndentedString(isMarkedResponse)).append("\n");
    sb.append("    noOfLikes: ").append(toIndentedString(noOfLikes)).append("\n");
    sb.append("    noOfDislikes: ").append(toIndentedString(noOfDislikes)).append("\n");
    sb.append("    replyCount: ").append(toIndentedString(replyCount)).append("\n");
    sb.append("    isLiked: ").append(toIndentedString(isLiked)).append("\n");
    sb.append("    isDisliked: ").append(toIndentedString(isDisliked)).append("\n");
    sb.append("    interactionType: ").append(toIndentedString(interactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

