/**
 * iEngage 2.0 API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.iengage.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.iengage.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * Milestone
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-18T06:00:03.235Z")
public class Milestone   {
  @SerializedName("milestoneId")
  private Long milestoneId = null;

  @SerializedName("milestoneTitle")
  private String milestoneTitle = null;

  @SerializedName("milestoneDescription")
  private String milestoneDescription = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("dueDate")
  private DateTime dueDate = null;

  @SerializedName("createdDate")
  private DateTime createdDate = null;

  @SerializedName("associationId")
  private Long associationId = null;

  @SerializedName("neverDue")
  private Boolean neverDue = false;

  @SerializedName("user")
  private User user = null;

  public Milestone milestoneId(Long milestoneId) {
    this.milestoneId = milestoneId;
    return this;
  }

   /**
   * Get milestoneId
   * @return milestoneId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMilestoneId() {
    return milestoneId;
  }

  public void setMilestoneId(Long milestoneId) {
    this.milestoneId = milestoneId;
  }

  public Milestone milestoneTitle(String milestoneTitle) {
    this.milestoneTitle = milestoneTitle;
    return this;
  }

   /**
   * Get milestoneTitle
   * @return milestoneTitle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMilestoneTitle() {
    return milestoneTitle;
  }

  public void setMilestoneTitle(String milestoneTitle) {
    this.milestoneTitle = milestoneTitle;
  }

  public Milestone milestoneDescription(String milestoneDescription) {
    this.milestoneDescription = milestoneDescription;
    return this;
  }

   /**
   * Get milestoneDescription
   * @return milestoneDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMilestoneDescription() {
    return milestoneDescription;
  }

  public void setMilestoneDescription(String milestoneDescription) {
    this.milestoneDescription = milestoneDescription;
  }

  public Milestone status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Milestone priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public Milestone dueDate(DateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(DateTime dueDate) {
    this.dueDate = dueDate;
  }

  public Milestone createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public Milestone associationId(Long associationId) {
    this.associationId = associationId;
    return this;
  }

   /**
   * Get associationId
   * @return associationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAssociationId() {
    return associationId;
  }

  public void setAssociationId(Long associationId) {
    this.associationId = associationId;
  }

  public Milestone neverDue(Boolean neverDue) {
    this.neverDue = neverDue;
    return this;
  }

   /**
   * Get neverDue
   * @return neverDue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getNeverDue() {
    return neverDue;
  }

  public void setNeverDue(Boolean neverDue) {
    this.neverDue = neverDue;
  }

  public Milestone user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Milestone milestone = (Milestone) o;
    return Objects.equals(this.milestoneId, milestone.milestoneId) &&
        Objects.equals(this.milestoneTitle, milestone.milestoneTitle) &&
        Objects.equals(this.milestoneDescription, milestone.milestoneDescription) &&
        Objects.equals(this.status, milestone.status) &&
        Objects.equals(this.priority, milestone.priority) &&
        Objects.equals(this.dueDate, milestone.dueDate) &&
        Objects.equals(this.createdDate, milestone.createdDate) &&
        Objects.equals(this.associationId, milestone.associationId) &&
        Objects.equals(this.neverDue, milestone.neverDue) &&
        Objects.equals(this.user, milestone.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(milestoneId, milestoneTitle, milestoneDescription, status, priority, dueDate, createdDate, associationId, neverDue, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Milestone {\n");
    
    sb.append("    milestoneId: ").append(toIndentedString(milestoneId)).append("\n");
    sb.append("    milestoneTitle: ").append(toIndentedString(milestoneTitle)).append("\n");
    sb.append("    milestoneDescription: ").append(toIndentedString(milestoneDescription)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    associationId: ").append(toIndentedString(associationId)).append("\n");
    sb.append("    neverDue: ").append(toIndentedString(neverDue)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

