/*
 * Stakeholder engagement API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iengage.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Sentiment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-24T14:38:21.881+05:30")
public class Sentiment {
  @SerializedName("veryNegative")
  private Double veryNegative = null;

  @SerializedName("negative")
  private Double negative = null;

  @SerializedName("neutral")
  private Double neutral = null;

  @SerializedName("positive")
  private Double positive = null;

  @SerializedName("veryPositive")
  private Double veryPositive = null;

  public Sentiment veryNegative(Double veryNegative) {
    this.veryNegative = veryNegative;
    return this;
  }

   /**
   * Get veryNegative
   * @return veryNegative
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getVeryNegative() {
    return veryNegative;
  }

  public void setVeryNegative(Double veryNegative) {
    this.veryNegative = veryNegative;
  }

  public Sentiment negative(Double negative) {
    this.negative = negative;
    return this;
  }

   /**
   * Get negative
   * @return negative
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getNegative() {
    return negative;
  }

  public void setNegative(Double negative) {
    this.negative = negative;
  }

  public Sentiment neutral(Double neutral) {
    this.neutral = neutral;
    return this;
  }

   /**
   * Get neutral
   * @return neutral
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getNeutral() {
    return neutral;
  }

  public void setNeutral(Double neutral) {
    this.neutral = neutral;
  }

  public Sentiment positive(Double positive) {
    this.positive = positive;
    return this;
  }

   /**
   * Get positive
   * @return positive
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPositive() {
    return positive;
  }

  public void setPositive(Double positive) {
    this.positive = positive;
  }

  public Sentiment veryPositive(Double veryPositive) {
    this.veryPositive = veryPositive;
    return this;
  }

   /**
   * Get veryPositive
   * @return veryPositive
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getVeryPositive() {
    return veryPositive;
  }

  public void setVeryPositive(Double veryPositive) {
    this.veryPositive = veryPositive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sentiment sentiment = (Sentiment) o;
    return Objects.equals(this.veryNegative, sentiment.veryNegative) &&
        Objects.equals(this.negative, sentiment.negative) &&
        Objects.equals(this.neutral, sentiment.neutral) &&
        Objects.equals(this.positive, sentiment.positive) &&
        Objects.equals(this.veryPositive, sentiment.veryPositive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(veryNegative, negative, neutral, positive, veryPositive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sentiment {\n");
    
    sb.append("    veryNegative: ").append(toIndentedString(veryNegative)).append("\n");
    sb.append("    negative: ").append(toIndentedString(negative)).append("\n");
    sb.append("    neutral: ").append(toIndentedString(neutral)).append("\n");
    sb.append("    positive: ").append(toIndentedString(positive)).append("\n");
    sb.append("    veryPositive: ").append(toIndentedString(veryPositive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

