/**
 * iEngage 2.0 API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.iengage.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.iengage.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * Task
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-18T06:00:03.235Z")
public class Task   {
  @SerializedName("taskId")
  private Long taskId = null;

  @SerializedName("taskTitle")
  private String taskTitle = null;

  @SerializedName("taskDescription")
  private String taskDescription = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("dueDate")
  private DateTime dueDate = null;

  @SerializedName("milestoneName")
  private String milestoneName = null;

  @SerializedName("groupType")
  private String groupType = null;

  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("assigneeUserId")
  private Long assigneeUserId = null;

  @SerializedName("neverDue")
  private Boolean neverDue = false;

  @SerializedName("user")
  private User user = null;

  public Task taskId(Long taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTaskId() {
    return taskId;
  }

  public void setTaskId(Long taskId) {
    this.taskId = taskId;
  }

  public Task taskTitle(String taskTitle) {
    this.taskTitle = taskTitle;
    return this;
  }

   /**
   * Get taskTitle
   * @return taskTitle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTaskTitle() {
    return taskTitle;
  }

  public void setTaskTitle(String taskTitle) {
    this.taskTitle = taskTitle;
  }

  public Task taskDescription(String taskDescription) {
    this.taskDescription = taskDescription;
    return this;
  }

   /**
   * Get taskDescription
   * @return taskDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTaskDescription() {
    return taskDescription;
  }

  public void setTaskDescription(String taskDescription) {
    this.taskDescription = taskDescription;
  }

  public Task status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Task priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public Task dueDate(DateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(DateTime dueDate) {
    this.dueDate = dueDate;
  }

  public Task milestoneName(String milestoneName) {
    this.milestoneName = milestoneName;
    return this;
  }

   /**
   * Get milestoneName
   * @return milestoneName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMilestoneName() {
    return milestoneName;
  }

  public void setMilestoneName(String milestoneName) {
    this.milestoneName = milestoneName;
  }

  public Task groupType(String groupType) {
    this.groupType = groupType;
    return this;
  }

   /**
   * Get groupType
   * @return groupType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupType() {
    return groupType;
  }

  public void setGroupType(String groupType) {
    this.groupType = groupType;
  }

  public Task groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public Task assigneeUserId(Long assigneeUserId) {
    this.assigneeUserId = assigneeUserId;
    return this;
  }

   /**
   * Get assigneeUserId
   * @return assigneeUserId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAssigneeUserId() {
    return assigneeUserId;
  }

  public void setAssigneeUserId(Long assigneeUserId) {
    this.assigneeUserId = assigneeUserId;
  }

  public Task neverDue(Boolean neverDue) {
    this.neverDue = neverDue;
    return this;
  }

   /**
   * Get neverDue
   * @return neverDue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getNeverDue() {
    return neverDue;
  }

  public void setNeverDue(Boolean neverDue) {
    this.neverDue = neverDue;
  }

  public Task user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.taskId, task.taskId) &&
        Objects.equals(this.taskTitle, task.taskTitle) &&
        Objects.equals(this.taskDescription, task.taskDescription) &&
        Objects.equals(this.status, task.status) &&
        Objects.equals(this.priority, task.priority) &&
        Objects.equals(this.dueDate, task.dueDate) &&
        Objects.equals(this.milestoneName, task.milestoneName) &&
        Objects.equals(this.groupType, task.groupType) &&
        Objects.equals(this.groupName, task.groupName) &&
        Objects.equals(this.assigneeUserId, task.assigneeUserId) &&
        Objects.equals(this.neverDue, task.neverDue) &&
        Objects.equals(this.user, task.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, taskTitle, taskDescription, status, priority, dueDate, milestoneName, groupType, groupName, assigneeUserId, neverDue, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    taskTitle: ").append(toIndentedString(taskTitle)).append("\n");
    sb.append("    taskDescription: ").append(toIndentedString(taskDescription)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    milestoneName: ").append(toIndentedString(milestoneName)).append("\n");
    sb.append("    groupType: ").append(toIndentedString(groupType)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    assigneeUserId: ").append(toIndentedString(assigneeUserId)).append("\n");
    sb.append("    neverDue: ").append(toIndentedString(neverDue)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

