/*
 * iEngage 2.0 API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iengage.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * User
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-27T14:33:47.218+05:30")
public class User {
  @SerializedName("userId")
  private Long userId = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("emailId")
  private String emailId = null;

  @SerializedName("profileImage")
  private String profileImage = null;

  @SerializedName("hasInterestUpdated")
  private Boolean hasInterestUpdated = false;

  @SerializedName("birthDate")
  private DateTime birthDate = null;

  @SerializedName("accessToken")
  private String accessToken = null;

  @SerializedName("currentUserFollowing")
  private Boolean currentUserFollowing = false;

  @SerializedName("currentUserFriend")
  private Boolean currentUserFriend = false;

  @SerializedName("equityScore")
  private Long equityScore = null;

  @SerializedName("extraData")
  private String extraData = null;

  public User userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public User firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public User lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public User emailId(String emailId) {
    this.emailId = emailId;
    return this;
  }

   /**
   * Get emailId
   * @return emailId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmailId() {
    return emailId;
  }

  public void setEmailId(String emailId) {
    this.emailId = emailId;
  }

  public User profileImage(String profileImage) {
    this.profileImage = profileImage;
    return this;
  }

   /**
   * Get profileImage
   * @return profileImage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProfileImage() {
    return profileImage;
  }

  public void setProfileImage(String profileImage) {
    this.profileImage = profileImage;
  }

  public User hasInterestUpdated(Boolean hasInterestUpdated) {
    this.hasInterestUpdated = hasInterestUpdated;
    return this;
  }

   /**
   * Get hasInterestUpdated
   * @return hasInterestUpdated
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasInterestUpdated() {
    return hasInterestUpdated;
  }

  public void setHasInterestUpdated(Boolean hasInterestUpdated) {
    this.hasInterestUpdated = hasInterestUpdated;
  }

  public User birthDate(DateTime birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(DateTime birthDate) {
    this.birthDate = birthDate;
  }

  public User accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * Get accessToken
   * @return accessToken
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public User currentUserFollowing(Boolean currentUserFollowing) {
    this.currentUserFollowing = currentUserFollowing;
    return this;
  }

   /**
   * Get currentUserFollowing
   * @return currentUserFollowing
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCurrentUserFollowing() {
    return currentUserFollowing;
  }

  public void setCurrentUserFollowing(Boolean currentUserFollowing) {
    this.currentUserFollowing = currentUserFollowing;
  }

  public User currentUserFriend(Boolean currentUserFriend) {
    this.currentUserFriend = currentUserFriend;
    return this;
  }

   /**
   * Get currentUserFriend
   * @return currentUserFriend
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCurrentUserFriend() {
    return currentUserFriend;
  }

  public void setCurrentUserFriend(Boolean currentUserFriend) {
    this.currentUserFriend = currentUserFriend;
  }

  public User equityScore(Long equityScore) {
    this.equityScore = equityScore;
    return this;
  }

   /**
   * Get equityScore
   * @return equityScore
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEquityScore() {
    return equityScore;
  }

  public void setEquityScore(Long equityScore) {
    this.equityScore = equityScore;
  }

  public User extraData(String extraData) {
    this.extraData = extraData;
    return this;
  }

   /**
   * Get extraData
   * @return extraData
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExtraData() {
    return extraData;
  }

  public void setExtraData(String extraData) {
    this.extraData = extraData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.userId, user.userId) &&
        Objects.equals(this.firstName, user.firstName) &&
        Objects.equals(this.lastName, user.lastName) &&
        Objects.equals(this.emailId, user.emailId) &&
        Objects.equals(this.profileImage, user.profileImage) &&
        Objects.equals(this.hasInterestUpdated, user.hasInterestUpdated) &&
        Objects.equals(this.birthDate, user.birthDate) &&
        Objects.equals(this.accessToken, user.accessToken) &&
        Objects.equals(this.currentUserFollowing, user.currentUserFollowing) &&
        Objects.equals(this.currentUserFriend, user.currentUserFriend) &&
        Objects.equals(this.equityScore, user.equityScore) &&
        Objects.equals(this.extraData, user.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, firstName, lastName, emailId, profileImage, hasInterestUpdated, birthDate, accessToken, currentUserFollowing, currentUserFriend, equityScore, extraData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    emailId: ").append(toIndentedString(emailId)).append("\n");
    sb.append("    profileImage: ").append(toIndentedString(profileImage)).append("\n");
    sb.append("    hasInterestUpdated: ").append(toIndentedString(hasInterestUpdated)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    currentUserFollowing: ").append(toIndentedString(currentUserFollowing)).append("\n");
    sb.append("    currentUserFriend: ").append(toIndentedString(currentUserFriend)).append("\n");
    sb.append("    equityScore: ").append(toIndentedString(equityScore)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

