/*
 * Stakeholder engagement API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iengage.service;

import com.iengage.ApiException;
import com.iengage.client.model.VerveResponseNotificationList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificationApi
 */
@Ignore
public class NotificationApiTest {

    private final NotificationApi api = new NotificationApi();

    
    /**
     * Get list of notifications
     *
     * Return the list of notifications
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNotificationsTest() throws ApiException {
        String type = null;
        Integer start = null;
        Integer end = null;
        String loggedInUserId = null;
        String accessToken = null;
        String clientToken = null;
        String fields = null;
        VerveResponseNotificationList response = api.getNotifications(type, start, end, loggedInUserId, accessToken, clientToken, fields);

        // TODO: test validations
    }
    
    /**
     * Mark all notification as read
     *
     * Allows the user to mark all the notification as read
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void markAllNotificationAsReadTest() throws ApiException {
        String loggedInUserId = null;
        String accessToken = null;
        String clientToken = null;
        Boolean response = api.markAllNotificationAsRead(loggedInUserId, accessToken, clientToken);

        // TODO: test validations
    }
    
    /**
     * Mark notification as read
     *
     * Allows the user to mark the notification as read
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void markNotificationAsReadTest() throws ApiException {
        Long notificationId = null;
        String loggedInUserId = null;
        String accessToken = null;
        String clientToken = null;
        Boolean response = api.markNotificationAsRead(notificationId, loggedInUserId, accessToken, clientToken);

        // TODO: test validations
    }
    
    /**
     * Get notifications count
     *
     * Returns the notification count
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void notificationCountTest() throws ApiException {
        String type = null;
        String loggedInUserId = null;
        String accessToken = null;
        String clientToken = null;
        Long response = api.notificationCount(type, loggedInUserId, accessToken, clientToken);

        // TODO: test validations
    }
    
}
