/*
 * iEngage 2.0 API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iengage.service;

import com.iengage.ApiException;
import com.iengage.client.model.VerveResponseUserPoints;
import com.iengage.client.model.VerveResponseUserPointsList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RewardsApi
 */
@Ignore
public class RewardsApiTest {

    private final RewardsApi api = new RewardsApi();

    
    /**
     * Get list of top friends
     *
     * Returns the list top friends
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopFriendsTest() throws ApiException {
        Long userId = null;
        Integer start = null;
        Integer end = null;
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        VerveResponseUserPointsList response = api.getTopFriends(userId, start, end, requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
    /**
     * Get list of top users
     *
     * Returns the list of top users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopUsersTest() throws ApiException {
        Integer start = null;
        Integer end = null;
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        VerveResponseUserPointsList response = api.getTopUsers(start, end, requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
    /**
     * Get list of user points
     *
     * Returns the list of user points
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserPointsTest() throws ApiException {
        Long userId = null;
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        VerveResponseUserPoints response = api.getUserPoints(userId, requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
}
