/*
 * iEngage 2.0 API
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iengage.service;

import com.iengage.ApiException;
import com.iengage.client.model.User;
import com.iengage.client.model.VerveResponseAssociation;
import com.iengage.client.model.VerveResponseAssociationList;
import com.iengage.client.model.VerveResponseUser;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserAuthenticationApi
 */
@Ignore
public class UserAuthenticationApiTest {

    private final UserAuthenticationApi api = new UserAuthenticationApi();

    
    /**
     * Add device token
     *
     * Add device token to push notification from server
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addNotificationRegisteredIdTest() throws ApiException {
        String registeredId = null;
        String type = null;
        String clientToken = null;
        String requesterId = null;
        String accessToken = null;
        Boolean response = api.addNotificationRegisteredId(registeredId, type, clientToken, requesterId, accessToken);

        // TODO: test validations
    }
    
    /**
     * Add/Register new user
     *
     * Add/Register new user. Returns the user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUserTest() throws ApiException {
        String screenName = null;
        String emailId = null;
        String password = null;
        String clientToken = null;
        String firstName = null;
        String middleName = null;
        String lastName = null;
        Integer birthDay = null;
        Integer birthMonth = null;
        Integer birthYear = null;
        String additionInformation = null;
        VerveResponseUser response = api.addUser(screenName, emailId, password, clientToken, firstName, middleName, lastName, birthDay, birthMonth, birthYear, additionInformation);

        // TODO: test validations
    }
    
    /**
     * Authenticate User
     *
     * Authenticate with username &amp; password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authenticateTest() throws ApiException {
        String userName = null;
        String password = null;
        String clientToken = null;
        User response = api.authenticate(userName, password, clientToken);

        // TODO: test validations
    }
    
    /**
     * Change password
     *
     * Allows the user to change password. Returns true if successful
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changePasswordTest() throws ApiException {
        String currentPassword = null;
        String newPassword = null;
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        Boolean response = api.changePassword(currentPassword, newPassword, requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
    /**
     * Create association
     *
     * Create association. Returns the association
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAssociationTest() throws ApiException {
        String name = null;
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        VerveResponseAssociation response = api.createAssociation(name, requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
    /**
     * Delete user
     *
     * Allows the user to delete user. Returns the deleted user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        Long userId = null;
        String clientToken = null;
        VerveResponseUser response = api.deleteUser(userId, clientToken);

        // TODO: test validations
    }
    
    /**
     * Get list of associations
     *
     * Return the list of association
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssociationsTest() throws ApiException {
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        VerveResponseAssociationList response = api.getAssociations(requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
    /**
     * Logout
     *
     * Logout rest api session. Returns true if successful
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        String requesterId = null;
        String clientToken = null;
        String accessToken = null;
        Boolean response = api.logout(requesterId, clientToken, accessToken);

        // TODO: test validations
    }
    
}
